### ISSUE TITLE
is it configurable 

### ISSUE THREAD

**Issue by inikishev** [DeflatedPickle/MobCorpses#1]
will it lag i like that corpses don't despawn but not too much otherwise itll lag

**Comment by inikishev** [comment]
its valid as if the premises are true, the conclusion necessarily follows

**Comment by supersaiyansubtlety** [comment]
@idkman2021 
Breafly looking at the code, it looks like it won't cause much more lag than vanilla behavior. 
AFAICT corpses still count towards the mobcap, so you shouldn't have more mobs in-world after installing the mod. 
That does mean that this mod makes mob switches trivially easy to create (just have a full mobcap of corpses). 

Note that it's best to use complete sentences and thoroughly explain your question when creating an issue.
